import turtle as tur
def min(n,x):
    if n==0:
        return
    if n==1:
        tur.forward(x)
        tur.left(90)
        tur.forward(x)
        tur.right(90)
        tur.forward(x)
        tur.right(90)
        tur.forward(2*x)
        tur.left(90)
        tur.forward(x)
        tur.left(90)
        tur.forward(x)
        tur.right(90)
        tur.forward(x)
    else:
        min(n-1,x)
        tur.left(90)
        min(n-1,x)
        tur.right(90)
        min(n-1,x)
        tur.right(90)
        min(n-1,x)
        min(n-1,x)
        tur.left(90)
        min(n-1,x)
        tur.left(90)
        min(n-1,x)
        tur.right(90)
        min(n-1,x)
tur.penup()
tur.goto(-400, 0)
tur.pendown()
tur.speed(50)
min(4,10)
input()